### ISSUE TITLE
Notation examples

### ISSUE THREAD

**Issue by alexanderadam** [SEbbaDK/chorddown#1]
Will this be a port of [chordr](https://github.com/chorddown/chordr)?
I never heard of this notation before.
Do you have any examples how this look like?

**Comment by SEbbaDK** [comment]
This has nothing to do with chordr, in fact i had never heard of it before.
I will put up some examples of the format of chord files, but the idea is that textrepresentations of chordfiles that are readily available on the internet are already chorddown.

Tabs like http://tabz.dk/se.php?id=221 just need metadata added:

```
TITLE: Papirsklip
ARTIST: Kim Larsen

    C                    Dm
Når nu min verden bliver kold og forladt
G                        C
finder jeg trøst hos min kæreste skat
Am                  Dm
klipper motiver med drømme og saks
  G                             C
papirsilhouetter af den fineste slags
```

**Comment by alexanderadam** [comment]
Ah, I see. Thank you!
